processing/p5.js-sound

- src/soundfile.js
fix https://github.com/processing/p5.js-sound/issues/35
> fixes #35 (SoundFile loop bug in latest Chrome)

- examples/peakDetect/sketch.js
- examples/peakDetection_offline/sketch.js
- src/gain.js
- remove button on peakDetect, it was causing an error latest updates to the dom library
- redraw peaks on offline example
> fix to peakDetect and peakDetection_offline

- src/looper.js
As per discussion in issue #127 @therewasaguy removePhrase has been updated to use splice rather than split on the phrases array.
> Bug fix for issue 127 removePhrase method

- examples/FFT_linAverages/index.html
- examples/FFT_linAverages/sketch.js
- examples/FFT_logAverages/index.html
- examples/FFT_logAverages/sketch.js
- index.html
- src/fft.js
This is my implementation of the linear and logarithmic groupings of the spectrum that we had discussed in the past. It also includes a function for generating the octave bands dynamically (https://courses.physics.illinois.edu/phys193/labs/octave_bands.pdf) and two examples respectively. 
I use them already for my browser based music visualisations, i.e: https://mkontogiannis.github.io/p5.js-sketches/frequency_bars/
> Linlog averages

- src/fft.js
Added a function that allows users to be able to change the bin size/fftSize.
The only issue is if the user inputs an invalid parameter, but I pretty much mimicked the way the constructor does it.
> Change the fftSize on the fly!

- src/fft.js
- test/test.js
- test/tests/p5.FFT.js
- tweak how we initialize fft bins and smoothing (cc @TheBrenny)
- add some tests for p5.FFT
> add fft tests for smoothing and bins

- src/delay.js
- src/filter.js
doin the things I said I would do here https://github.com/processing/p5.js-sound/pull/178#discussion_r123121507 and here https://github.com/processing/p5.js-sound/pull/178#discussion_r123120735 cc @jvntf
> p5.Delay patch dispose method, p5.Filter module export

- examples/sound_loop/sketch.js
> patch sound loop example

- src/audioin.js
Adds missing YUIDoc properties
> Document properties of AudioIn

- src/looper.js
A little clarification, and also fixed inaccurate documentation.
Sorry for some useless changes in style I accidentally made :|
> Fixed documentation

- examples/genetic_music/index.html
- examples/genetic_music/sketch.js
- index.html
New example demonstrating the use of genetic algorithms to generate musical content.
> Genetic music

- examples/markov_music/index.html
- examples/markov_music/sketch.js
- index.html
Add example to demonstrate the use of Markov chains to model and generate musical sequences.
> Markov music

- .travis.yml
- README.md
following up on https://github.com/processing/p5.js-sound/pull/344/files
> adding travis config to travis-ci.com

- src/fft.js
> Removed unnecessary lines

- src/audioin.js
Applied changes from https://github.com/processing/p5.js/pull/4044
> Typo in documentation

- test/tests/p5.SoundFile.js
solves 
#422 
removed the unnessary tests of getLevel Method of p5.SoundFile
> removed the testing of getLevel Method of p5.SoundFile

- src/fft.js
> fixed typo in p5.fft 

- src/panner3d.js
fixes 
#464 
before :
after  :
> fixed broken links in p5.panner3D

- src/audioin.js
> fixed the broken anchor tag in audioin.js

- src/signal.js
> fixed typo in P5.signal documentation Page !

- src/listener3d.js
`Effect` variable was initilized but never used ! 
so removed it !!
> removed initilized but never used variables from listner3d.js

- src/app.js
- src/effect.js
@therewasaguy @kyle1james  please review this pr!
> replacement of es5 functions to es6 class def feat P5.Effect

- src/app.js
- src/distortion.js
@therewasaguy  @kyle1james  please review this pr !
> replacement of es5 functions to es6 class def feat P5.distortion

- src/eqFilter.js
@therewasaguy || @kyle1james  please review this pr
> replacement of es5 functions to es6 classes feat p5.eqfilter

- src/app.js
- src/eq.js
@therewasaguy @kyle1james please review this pr
> replacement of es5 functions to es6 classes feat p5.Eq

- package-lock.json
- src/app.js
- src/compressor.js
- src/distortion.js
- src/effect.js
- src/eq.js
- src/eqFilter.js
- src/gain.js
@therewasaguy  @kyle1james Please review this PR.
> replacement of es5 functions to es6 classes feat p5.Gain

- src/app.js
- src/panner3d.js
@therewasaguy @kyle1james Kindly review this PR.
> Replacement of es5 functions to es6 classes feat p5.panner3D

- src/app.js
- src/helpers.js
- src/polysynth.js
@therewasaguy @kyle1james Kindly review this PR.
> Replacement of es5 functions to es6 classes feat p5.polySynth

- src/app.js
- src/peakDetect.js
@therewasaguy @kyle1james Kindly review this PR.
> Replacement of es5 functions to es6 classes feat p5.peakDetect

- src/app.js
- src/listener3d.js
@therewasaguy @kyle1james Please review this PR.
> Replacement of es5 functions to es6 classes feat p5.listener3D

- src/app.js
- src/onsetDetect.js
@therewasaguy @kyle1james Kindly review this PR.
> Replacement of es5 functions to es6 classes feat p5.onsetDetect

- src/app.js
- src/metro.js
@therewasaguy  @kyle1james  another one !
> Replacement of es5 functions to es6 classes feat p5.metro

- src/app.js
- src/filter.js
@therewasaguy  @kyle1james here we go with one more in a row !
> replacement of es5 functons to es6 classes feat p5.filter

- test/test.js
This resolves some issues I was having running the tests in Chrome
> requiring user interaction before running tests, per chrome autoplay policy

- src/app.js
- src/pulse.js
@therewasaguy  @kyle1james 
please review the PR ! 
though we are not having unit test for p5.Pulse ! 
it seems fine to me !
> replacement of es5 functions to es6 classes feat p5.Pulse

- src/app.js
- src/noise.js
@therewasaguy  @kyle1james  
okay this is small one !
> replacement of es5 functions to es6 classes feat p5.noise

- src/app.js
- src/master.js
@kyle1james @therewasaguy  
okay this is a small boy !
> replacement of es5 functions to es6 classes feat Master.js

- src/app.js
- src/looper.js
@therewasaguy @kyle1james 
please review this PR !
> replacement of es5 functions to es6 classes feat p5.Phrase , p5.Part , P5.Score

- src/app.js
- src/reverb.js
@therewasaguy  @kyle1james 
please review this PR!
> replacement of es5 functions to es6 classes feat p5.Reverb ,p5.Convolver

- src/app.js
- src/helpers.js
@therewasaguy @kyle1james  
please review this PR !
okay !  maybe this would be the last one for the gsoc goals !
> decoupled helpers method from p5 in helper.js and coupled them separetly in app.js

- src/app.js
- src/helpers.js
@therewasaguy there was a wrong resolve while merging , so build process was not passing 
fixed it now !
is there any other way to correct the mistake , like other than making a separate PR , couldn't i make changes in https://github.com/processing/p5.js-sound/pull/540 ( i am not sure cz it has been merged! )
> fixed error while merging 

- src/amplitude.js
There was an apparent issue with one of the examples on [p5 js reference](https://p5js.org/reference/#/p5.Amplitude). According to the following [issue](https://github.com/processing/p5.js-sound/issues/552), I have made appropriate changes to the example.
Let me know about any changes I should make. :)
> fixes issue #552

- src/amplitude.js
- src/fft.js
Made the grammatical corrections in the documentation as requested in issue #549. Let me know about any changes. :)
> Fixes #549

- src/app.js
- src/helpers.js
- src/panner.js
@endurance21 Kindly review the changes!
> Fixed some linting errors

- examples/amplitude_analysis/index.html
- examples/array_of_notes/index.html
- examples/array_of_notes_soundloop/index.html
- examples/audioIn_Multiple_Sources/index.html
- examples/autoCorrelation/index.html
removed import script statement in html form first five examples
> removes depencies of dom-library for first 5 examples #577

- test/tests.js
- test/tests/p5.Helpers.js
@therewasaguy can you please! review this. I also tried to add the test for the _checkFileFormats but I am not able to debug it. Is there any way to put the breakpoint in test or console.log?
> Adding test for helper function

- test/tests/p5.Amplitude.js
- test/tests/p5.AudioIn.js
- test/tests/p5.AudioVoice.js
- test/tests/p5.Compressor.js
- test/tests/p5.Delay.js
- test/tests/p5.Distortion.js
- test/tests/p5.EQ.js
- test/tests/p5.Effect.js
- test/tests/p5.FFT.js
- test/tests/p5.Filter.js
- test/tests/p5.MonoSynth.js
- test/tests/p5.Oscillator.js
- test/tests/p5.PolySynth.js
- test/tests/p5.Reverb.js
- test/tests/p5.SoundFile.js
- test/tests/p5.SoundRecorder.js
@therewasaguy I replaced all the var keywords with const and let. I am attaching a screenshot of the test of the main and my branch. Some tests are failing in main that's why it is also failing in my changes also. I will fix it. 
can you please review this? Waiting for your suggestion :)
Screenshot Master
Screenshot my branch
> Removing var keyword from test code

- .github/workflows/ci-lint.yml
- .github/workflows/ci-test.yml
- .travis.yml
this is the last p5.js project using travis (which we now have to pay for), would love to get this on GitHub Actions too!
> Migrate to GitHub Actions for CI

- src/polysynth.js
fixes #599 
- Changed secondsFromNow to zero
- changed velocity to 0.1
Though it'll work even if the velocity is not set to 0.1, I think it'll make the code much understandable.
> fixed PolySynth  play() bug 

- examples/spatial_panning_listener/sketch.js
- src/app.js
- src/looper.js
- src/polysynth.js
- src/reverb.js
- src/soundfile.js
- test/tests.js
I isolated the commits from my previous 2 PRs(week-3,4 week-6,7) that consists of various bug fixing that I felt are potential bugs.
> Bug fixing

- src/envelope.js
> Correct typo semicolon

- src/amplitude.js
- src/soundfile.js
Documented the ``` getPlaybackRate``` method in p5.SoundFile
> Documentation of getPlaybackRate method

- src/helpers.js
Documented the ```noteToFreq``` method in the helpers.js file.
> documentation of noteToFreq method

- src/soundfile.js
Documented the ```setPitch``` method in p5.SoundFile
> documentation of setPitch method

- src/monosynth.js
- test/tests/p5.MonoSynth.js
Resolves #663 
Added `setType(type)` and `getType()` to monosynth
Added documentation and tests
> Added setType and getType to MonoSynth

- src/soundfile.js
Regarding: Add the functionality for pitch return #699 issue.
> added getPitch() function

- src/soundfile.js
Regarding: getPitch() documentation requires #701 issue.
> getPatch() documentation

- src/soundfile.js
Regarding: Example for setPitch() #703  issue.
> setPitch_example

- src/oscillator.js
Now example reference is added for the pan in the oscillator class.
> example reference added

- lib/p5.sound.js
Changes:
- Mostly adding a capital letter to the start of the sentence.
- Adding some extra information to params and/or return values.
- Remove additional 'optional' texts
- Remove repeated words in the same sentence
> Update p5 sound documentation information

- src/soundfile.js
Documented the ```getVolume``` method in the soundFile.js file.
> documented getVolume()

- src/audioVoice.js
Closes #705 
- Added `setADSR()` default method to AudioVoice class
> add setADSR() default method to AudioVoice

- src/noise.js
- Added new example to p5.Noise 
- setType() 'type' is now not documented as optional
- Added documentation to `getType()`, `start()`, `stop()` and `dispose()`
> add example and documentation to Noise 

- test/tests/p5.Gain.js
updated gain test and added test to set the output level of gain Node.
> (Chore) : Added test to set the output level of gain Node

- src/peakDetect.js
The onPeak docs where awkward - I'm not sure this is better, but I wouldn't need to read this code with this - please feel free to edit the PR to make it acceptable!
> Clear onPeak docs

- src/compressor.js
added example to `Compressor` docs
> add compressor example

- src/audioin.js
added description for the various fields of `p5.AudioIn reference` such as `stream`, `mediaStream` and `currentSource`
resolves #724
> (Docs): Updated various fields in the p5.AudioIn reference

- src/oscillator.js
- test/tests/p5.Oscillator.js
Refer PR: #653 (resolved merge conflicts in existing )
Resolves https://github.com/processing/p5.js-sound/issues/513
- Fixed incorrect `sigChain helper` function, which inserts or modifies a node into a signal chain
- Fixed incorrect math in `scale `method
- Added tests
> (Chore): Fixed Oscillator add, mult, scale methods

- src/audioVoice.js
Add missing documentation for `AudioVoice.dispose()`
> Add documentation for `AudioVoice.dispose()`

- README.md
Update information in the readme, for the newcomers and project visitors, updated and added links to p5.js social communities.
> (Docs): Improved docs and updated info for repo visitors
