processing/p5.js-sound

lib/p5.sound.js

I am an audio noob so I'm not sure if this is right, but it *seems* like a typo...

Fix typos in docs for Signal.prototype.scale

---

src/fft.js

I also tried to do the auto-documentation thing - I think I did it correctly.

added a getCentroid() function to return the spectral centroid of an fft

---

src/audioin.js
src/oscillator.js
src/soundRecorder.js

- add AudioIn error handler for ios and safari
- fix audioIn stop (#105)
- add audioin documentation
- fix saveSound for stereo (#112)
- tweak oscillator memory management

AudioIn fixes, better oscillator memory management, saveSound can be mono

---

src/soundRecorder.js

According to the WAV spec, the number that goes right after 'RIFF' is 36 + ... not 44 + ... - here's an excerpt from the spec:
The canonical WAVE format starts with the RIFF header:
0         4   ChunkID          Contains the letters "RIFF" in ASCII form (0x52494646 big-endian form).
4         4   ChunkSize        36 + SubChunk2Size, or more precisely: 4 + (8 + SubChunk1Size) + (8 + SubChunk2Size) This is the size of the rest of the chunk following this number.  This is the size of the entire file in bytes minus 8 bytes for the two fields not included in this count: ChunkID and ChunkSize.

Fixed WAV format in soundRecorder.js:saveSound()

---

src/master.js

Closes #130 
Quick straightforward PR to remove a warning due to an excessive value for the compressor ratio. Previously was just clamping down to 20 so switching to 20 should result in no change.

Resolve `DynamicsCompressor.ratio.value` clamping warning

---

examples/mixingSounds/sketch.js

Replaced calls to connectSource with setInput.
This example was still calling p5.Gain.connectSource instead of
p5.Gain.setInput introduced in commit
41d6d1dccd8782410b460fcf7c938378efae898a causing the sketch not to run.

Fixes mixingSound Example

---

src/soundfile.js

Fixes #193.
This PR applies the logic in https://github.com/processing/p5.js/pull/2008 to the `loadSound()` function.
There is a full discussion of the issue in the main p5.js library's issue queue, including an example of how the current implementation breaks, at https://github.com/processing/p5.js/issues/2005#issuecomment-309017764.

Applying new loadXX _decrementPreload logic to loadSound

---

src/panner.js
src/soundfile.js

- fix #182 where `setVolume` would be overridden on `play()`. Now play calls `setVolume()` and also `rate()`.
- cleanup SoundFile `rate` and `reverseBuffer` methods
- bring back panner inputChannels method
cc @nbrosowsky @dhowe

SoundFile: setVolume and rate on play 

---

src/audioin.js
src/compressor.js
src/delay.js
src/distortion.js
src/effect.js
src/env.js
src/filter.js
src/helpers.js
src/looper.js
src/master.js
src/oscillator.js
src/peakDetect.js
src/reverb.js
src/signal.js
src/soundRecorder.js
src/soundfile.js

this fixes a few issues with the yuidoc @type declarations. mostly, `@type` doesn't use '{}' or take a description (even though the yuidoc docs suggest it does). also a few p5 namespace fixes.

yuidoc @type fixes

---

src/amplitude.js
src/audioin.js
src/compressor.js
src/delay.js
src/distortion.js
src/effect.js
src/errorHandler.js
src/fft.js
src/filter.js
src/looper.js
src/master.js
src/noise.js
src/oscillator.js
src/pulse.js
src/reverb.js
src/signal.js
src/soundfile.js

this one cleans up the constructors a little and adds `@extends` where appropriate. constructors actually return void, so i removed the `@return` attributes from them.
i also modified the item view template to render a fake **'Returns:'** section for constructors:
https://github.com/Spongman/p5.js/commit/631439cb9ffba0a7127968115724f121e0ae234c

docs: remove @returns from @constructors, add @extends

---

Gruntfile.js
src/filter.js
src/oscillator.js

- Grunt watch and connect tasks use different ports than p5.js-website's watch task so that we can run both at the same time
- update docs for subclasses of filter and oscillator (following up on https://github.com/processing/p5.js-sound/pull/199#discussion_r126860732)

Docs subclasses

---

src/delay.js

found bug-- only left channel was getting connected under default Delay construction

graph routing error

---

src/compressor.js
src/delay.js
src/distortion.js
src/effect.js
src/filter.js
src/reverb.js

re-opening this PR because of some new fixes, and updated docs for all effects.
yuidoc tag @extends does not seem to render the relevant methods from the base class (does not seem to be happening for p5 either)-- have included links to base class / methods in the effect classes.

Update docs again

---

src/effect.js
test/tests/p5.Effect.js

p5.Effect dispose() gets rid of `wet` and `_drywet` nodes.
@jvntf I'm also wondering if `wet` should be `_wet' (private)?

p5.Effect disposes wet dry nodes

---

src/panner3d.js

- fix duplicate method yuidoc definitions
- update p5.Panner3D description
@jvntf this fixes an issue when running `grunt yui` to generate the docs in p5.js repo
`
Warning: for Spatializer.positionZ() defined in lib/addons/p5.sound.js:8442, additional overloads should have no description ("<p>Getter and setter methods for orient coordinates</p>\n" !== "") Use --force to continue.
`
...but I'm not sure of the best way to get sub-properties of the p5.Panner3d.panner (distanceModel, panningModel) to display properly in our reference pages.

update docs for Panner3d

---

src/oscillator.js

Fix comment in p5.Oscillator reference example, https://p5js.org/reference/#/p5.Oscillator.

Fix comment in p5.Oscillator reference example

---

src/helpers.js

when the combined `data.json` file is generated, the source file for the `p5` class was listed as `addons/p5.sound.js`. this is because of this bogus `@class p5` directive in `src/helpers.j`.
this PR switches this to a `@for` directive which indicated that these are additional methods for a class defined elsewhere...

fix documentation bug

---

src/fft.js

I fixed a broken link the getEnergy() example html, which figures as commented out text in the codebase, line 302. All the other mods bellow are just from my IDE which is set up w/Prettier which swapped out some double quotes for singles (sorry about that!) 
That broken link has been bothering me for ages, hopefully you don't mind that I fixed such a small thing!

fixed broken link in getEnergy() example

---

src/soundLoop.js

Hey all,
Noticed we were missing a paren after the loadSound call on the p5.SoundLoop example sketch. This was breaking the example and the formatting on the p5 reference site.
All the best
Dex

Fix missing paren on p5.SoundLoop example sketch

---

src/fft.js

This pull request resolves the issue listed in processing/p5.js-website#160 & processing/p5.js#2591
In the [reference docs](https://p5js.org/reference/#/p5.FFT/getCentroid), the canvas overlaps with the example code. 
Fixed by reducing the size of the canvas to the default size of 100x100. I made the text smaller so it would fit properly on the small canvas.
I hope this is the right place to make this update.

fix getCentroid reference page alignment

---

src/monosynth.js

As pointed out in https://github.com/processing/p5.js-sound/issues/259#issuecomment-372107373 as well as https://github.com/processing/p5.js-sound/issues/245, there is a stray `monosynth.loadPreset('simpleBass')` method being called in the inline documentation for MonoSynth, which produces an error "monosynth.loadPreset is not a function".
This PR fixes the error by removing the line.

MonoSynth inline docs: remove loadPreset()

---

src/gain.js
src/peakDetect.js
src/reverb.js
src/soundfile.js

this PR fixes a few issues found when running the p5.js reference tests in browser:
- ensures `loadSound()` is called from `preload`. this prevents the p5 instance from being removed before the load has completed which can cause issues especially during the tests when multiple p5 instances are created one after the other.
- ensures that `createConvolver()` calls `_decrementPreload`. this allows preload functions that create convolvers to complete.
- fixes some asset paths.

Preload fixes

---

src/monosynth.js
src/polysynth.js
test/test.js
test/tests/p5.AudioVoice.js
test/tests/p5.MonoSynth.js
test/tests/p5.PolySynth.js

Dug into the synth classes in response to https://github.com/processing/p5.js-sound/issues/266, they have a solid foundation and I'm excited to do more with them!
Apologies for this somewhat large PR, I'll break it down into smaller pieces...
- fix some dispose issues that made examples break if you try to reset them. (I think a better solution for this might be to set a flag on the dispose method so that everything can only be disposed of once)
- update monoSynth and PolySynth inline examples to use Note Strings as discussed in https://github.com/processing/p5.js-sound/issues/266
- fix PolySynth currentVoice counting as discussed in https://github.com/processing/p5.js-sound/issues/266 - the fixes are [here](https://github.com/processing/p5.js-sound/commit/762c76fb1fae9447841eeb84bec687ec6 …

monoSynth and polySynth fixes + examples

---

src/soundLoop.js

Fix for the error described in #286 . Small mistake, forgot to use `ac.currentTime` to schedule the pause.

Fix bug in pause, forgot to use currentTime to schedule pause

---

src/polysynth.js

Fixes small error in docs: `PolySynth.setADSR` does not have a `note` input parameter, but the docs say that it does. This removes that extra parameter in the docs.

Remove wrong parameter 'note' in polysynth setADSR docs

---

examples/_monosynth_basic/sketch.js
src/audioVoice.js
src/helpers.js
src/monosynth.js
src/polysynth.js

- add a `DEFAULT_SUSTAIN` to the monosynth so that we can call `play('a4')`  without providing any additional parameters
And a few small tweaks:
- move `noteToFreq` to helpers
- fix octave in ANSI note conversion (`value += 12 * (octave -1);`)
- allow for lower case ANSI notes like "a4"
- dispose of polysynth TimelineSignal on noteRelease - otherwise these were not getting garbage collected and a potential memory issue

synth play method has a default sustain

---

fragments/before.frag

Title says it all; #288 carried out renaming of Env class to Envelope across the repo, but missed out this documentation fragment.

Rename Env to Envelope in the documentation fragment

---

src/master.js
src/monosynth.js

This should fix https://github.com/processing/p5.js-sound/issues/301 
- Monosynth envelope ramps `this.output.gain` — the audio param — instead of `this.output`
- [Update master limiter knee and threshold](https://github.com/processing/p5.js-sound/commit/9607a544e94246649f3a724425121762786dcae6) so that it is better suited to prevent clipping. Specifying a sharp `knee` value makes a big difference, as does lowering the ratio slightly. We don't want to change the quality of sound unless it's nearly clipping.
- remove some unused monosynth properties (_isOn and filter)

patch monosynth velocity

---

src/soundRecorder.js

as my need is recording sound by microphone, then appending it to DOM for preview before it is downloaded. a temporary blob url is the choice.

Added saveSoundToBlob() to soundRecorder.js

---

src/helpers.js
src/soundRecorder.js
src/soundfile.js

- move .wav conversion from p5.SoundRecorder to helpers module
- add  `save` and `saveBlob` method to SoundFile
- document the global `saveSound` method (it was listed under p5.SoundRecorder but is actually part of p5.prototype)
- p5.SoundFile's `saveBlob` method can probably replace the global `saveSoundAsBlob` added in https://github.com/processing/p5.js-sound/pull/312 —@wahengchang does this sound like a good approach to you?

add `save()` and `saveBlob()` methods to SoundFile. Move .wav conversion to helpers.js

---

src/soundfile.js

- adds some checks to SoundFile callbacks to prevent crashes during async callbacks completing on disposed objects
- moves `loadSound` call to `preload()` in doc sample

prevent crashes during completion of callbacks on disposed SoundFiles

---

src/helpers.js

The ```convertToWav(audioBuffer)``` function hardcoded 44100 for the sample rate, which saved the buffer to a file correctly, but set the sample rate wrong if the buffer's sample rate was different (e.g., 48000). One could just alter the file after, but this saves the buffer to a wave file with the sampleRate from the AudioContext.

Used sampleRate from AudioContext for saving rather than hardcoded 44100

---

src/soundfile.js

Remove bad console call

---

Gruntfile.js
package-lock.json
package.json
webpack.config.js

p5 generates p5.sound documentation by looking at the p5.sound.js file in the addons directory [here](https://github.com/processing/p5.js/blob/3da1b0286a7b99d4342e209ee1ba3f3286d5dff9/Gruntfile.js#L235).
Unfortunately, our new webpack build adds comments that confuse the yuidoc parser.
@oshoham and I spent some time looking at possible solutions. We tried to remove extraneous comments from the webpack build, but this caused more problems.
The solution we came to for now is to separate out the comments using the "extractComments" options, which is designed to extract a license file. We'll include this file with updates to the p5 repo. Then p5 will pick up the comments from that file when it generates the reference pages.
We'd need to either remove comments from the un-minified file, or …

remove webpack comments from build (for yuidoc)

---

src/audioWorklet/index.js

This Promise `return ac.audioWorklet.addModule(objectURL)` was throwing an error if the worklet with that name had already been registered on the page.
We run into this issue when p5 is in "instance mode" (i.e. on the documentation examples at p5js.org) because the "init" callback can run multiple times for each instance.
cc @oshoham

only add audioworklet modules once

---

src/soundfile.js

Fix deletion of array elements in iteration.
- Add the second argument `1` for `splice`
- Iterate in reverse order since the index changes by `splice`
[see this logic works](https://jsfiddle.net/osfdt0z6/)

Fix deletion of array elements in iteration

---

src/soundfile.js

- `p5.SoundFile.jump()` should not start playback
- Fixes a bug in `p5.SoundFile.reverseBuffer()` where calling that method would trigger playback unexpectedly

soundfile.jump: only jump if currently playing

---

src/soundfile.js

- the first cue would not fire because `_prevUpdateTime` was undefined
- possible fix for #371 addCue not triggering function calls

soundfile: patch addCue bug

---

fragments/before.frag
src/amplitude.js
src/audiocontext.js
src/audioin.js
src/delay.js
src/envelope.js
src/eq.js
src/fft.js
src/filter.js
src/gain.js
src/helpers.js
src/looper.js
src/master.js
src/monosynth.js
src/oscillator.js
src/polysynth.js
src/pulse.js
src/reverb.js
src/signal.js
src/soundLoop.js
src/soundRecorder.js
src/soundfile.js

- Update inline examples to start audio context on a user gesture, either by playing a sound (`soundFile.play()` / `oscillator.start()`) or by explicitly calling `userStartAudio()` https://github.com/processing/p5.js-sound/issues/388
- Use `let` in examples, instead of `var`, but not `const`, as discussed in this issue where it was decided to use `let` exclusively in examples: https://github.com/processing/p5.js/issues/3877
- Update styles for consistency with other p5 inline examples
So far, some examples use `soundFile.play()` or `oscillator.start()` rather than a potentially redundant call to `userStartAudio()`. It _might_ be worth that redundant call, because the difference between methods that call "start" on a WebAudio node (thus enabling audio on a user gesture) and those that do …

update inline examples (#388)

---

Gruntfile.js

Decomment is necessary for the p5js website inline documentation to parse the jsdoc comments, but not the webpack comments

Grunt dev task also decomments

---

src/soundfile.js

Fixes #456 
The `getblob` and `http` links had an extra "/docs" in the href due to which they both gave a 404 error. This PR fixes it.

Fixed the getblob & http links in p5.SoundFile

---

src/envelope.js

fixes #467
removed hard coded `(optional)` 
because writing [v2] is understood by yuidocs as optional parameter and it automatically writes there '(Optional)` for us !

fiexed typo in ramp method documentation

---

examples/peakDetect/sketch.js
examples/peakDetection_offline/sketch.js

The method to print to the native console that is println has been deprecated and that it must be replaced with a proper method which is "console.log" for native js consoles and for p5 web editor too .
> https://github.com/processing/p5.js/issues/1614
> https://discourse.processing.org/t/is-println-deprecated/19929

replaced depracated println method with console.log

---

src/signal.js

fixes #471 
before :
`carrier.start()`  was placed inside setup function, and as soon as the script get rendered , user hears a all of a sudden sound of carrier node without the user consent :grimacing: !! 
after:
`carrier.start()` has been placed inside the `canvasPressed()` which ensures that output signal is heard by user when it Presses the canvas ! :grinning:

fixed abnormal behaviour of audio output in p5.signal example

---

package-lock.json

i cloned this repo and ran `npm install`
and it had 396 vulnerabilities
after running `npm audit fix`
now we have only 36 :)
the remaining ones require more manual work and might be breaking changes

npm audit fix to fix vulnerabilities

---

src/audioin.js

fixes #384, including links mentioned on setSource() and getSources()

fix links on documentation of p5.AudioIn methods

---

README.md
fragments/before.frag
todo.md

A minor change to update the links to point to the repository under the `processing` organization (even though GitHub handles redirects).

Update the links to the GitHub repository

---

src/soundfile.js
test/tests/p5.SoundFile.js

fixed extra callback calls in while using cue to the soundFiles

---

test/test.js
test/tests/p5.Master.js

added unit test for the methods in p5.master 
1.checks for value mastervolume ( set and returned values)
2.checks  for  fading effect of setting masterVolume 
3.checks for setting the masterVolume after the given time t 
results 
@therewasaguy please review this pr!

added unit test for p5.master

---

src/app.js
src/delay.js

@therewasaguy  @kyle1james  please review this pR!

replacement of es5 functions to es6 classes featuring p5.delay

---

src/app.js
src/soundLoop.js

@therewasaguy  @kyle1james  please review the PR!

replacement of es5 functions to es6  classes feat p5.SoundLoop

---

src/audioWorklet/ringBuffer.js

An error is logged to the console when calling `p5.SoundFile.play()`
It happens because the SoundFileProcessor sends `[undefined]` to the `ringBuffer` some of the time. 
https://github.com/processing/p5.js-sound/blob/master/src/audioWorklet/soundFileProcessor.js#L18
Causing the `AudioWorkletNode` `onmessage` callback to not fire, which results in `p5.SoundFile.currentTime()` always returning 0.
https://github.com/processing/p5.js-sound/blob/master/src/soundfile.js#L1353-L1364
This change removes the console error and make `currentTime()` behave correctly.

Default to 0 if arraySequence[0] is undefined

---

src/app.js
src/panner.js
src/soundfile.js

all test working fine ! 
@therewasaguy  @kyle1james please review this pr!

replacement of es5 functions  to es6 classes feat p5.soundFile

---

src/app.js
src/helpers.js
src/soundRecorder.js
test/test.js

* moved savesound () method from soundRecorder.js to helpers.js because it is being used in soundFile.js and there is not a signle sense to keep it in soundRecorder.js 
* replacemend work in soundRecorder.js
* made p5.prototype.saveSound  = saveSound from helpers to maintain code backward compatiblity ! 
@therewasaguy  @kyle1james  please review this Pr !
thanks !

replacement es5 classes to es6 classes feat p5.SoundRecorder

---

src/app.js
src/oscillator.js

@therewasaguy  @kyle1james  tests are smooth 
need a review here ! thanks!

replacement es5 functions to es6 classes feat p5.Oscillator

---

src/app.js
src/panner.js

@therewasaguy @kyle1james  Please review this PR.

Replacement of es5 functions to es6 classes feat p5.panner

---

lib/p5.sound.js

Resolves #556 
Changes:
Earlier 'parameter' was spelled incorrectly in the bpm field of [**p5.SoundLoop reference**](https://p5js.org/reference/#/p5.SoundLoop)
This pr resolves that issue

Fix typo in bpm field of p5.soundLoop reference

---

.gitignore

It would be inconvenient if git tracks the changes made in the `lib/` directory after each build.
**Changes:**
- added `lib/p5.*` to `.gitignore`
[p5.js](https://github.com/processing/p5.js) repository also does not track the library after build (see [here](https://github.com/processing/p5.js/blob/main/.gitignore#L6)). @endurance21 I would love to hear your thoughts on this :)

add lib/p5.* to .gitignore

---

src/soundfile.js

As codebase now uses AudioWorklet nodes instead of ScriptProcessor nodes. We should get rid of comments related to ScriptProcessor nodes.
Area affected: src/soundfile.js

Removed obsolete comments of initCounterNode in soundfile.js

---

Gruntfile.js
templates/pre-commit-hook.js

- Added template in order to run grunt lint only if there are staged changes.
- Added grunt lint-nofix task to run linter in no-fix mode.
- Fixed some linting changes too.
I have added the template @endurance21, which is working just like we wanted it to work.
Kindly review the changes @endurance21  @therewasaguy @montoyamoraga @kyle1james  
And just let me know if you need any further changes.

Optimized pre-commit-hook action.

---

src/soundfile.js

- Allow the BufferSourceNode EventListener to deliver onend when stopAll
is called. _clearOnEnd will call _onended and remove the
EventListener.
Signed-off-by: Robert Collins <robertc@robertcollins.net>

Bug #571: fix excess onend events

---

src/soundfile.js

Fixes https://github.com/processing/p5.js-sound/issues/412
There is a `if (!self.panner) return;` check at https://github.com/processing/p5.js-sound/blob/b291d88d9bcb45905852fabbcbb2d8fff0999c00/src/soundfile.js#L1547 which always fails, because `self` variable is undefined.
Not sure if this is proper way to fix this, but it seems pretty obvious and the callback starts to work. 🙂

fix SoundFile.processPeaks()

---

src/audioWorklet/index.js

reffering to https://github.com/processing/p5.js-sound/issues/592

fixed repeated initilisation of audioWorklet

---

src/amplitude.js

In  PR #563 the name of function was changed but backward compatibility was not ensured.
https://github.com/processing/p5.js-sound/pull/563/commits/498061ee4d54b8886e6273b30df93e1ee5f10730
Added correct function name at required place.

Fixed function name mismatch in reference page of p5.Amplitude

---

src/audioin.js

unwanted variable name .
it should be `useStartAudio` instead of `useraudiocontextstart` in inline example of p5.audioin
corrected the variable name

Fixes in Reference Examples 

---

src/helpers.js
test/tests/p5.MonoSynth.js

@therewasaguy The freq of note 'A2' is 55 but we are checking in test 110.
we can test 110 by
```monoSynth.oscillator.freq(110,0.001);```
and then in expect we can do
``` expect(monoSynth.oscillator.freq().value).to.equal(110);```
but I think 55 is also good
This test fails sometime because it compares the default value to 55 if you run the test multiple times I think it is due to Mocha running the function rightaway and our frequency is not set yet.
screenshot
of the passing test

Fixing test in monoSynth.js

---

examples/record/sketch.js
index.html
src/looper.js
src/soundRecorder.js

Fixes #627,
Fixed the example in both the examples folder's file and also the inline code.
To make sure that the mic is called only after the user's interaction with the example, I've moved the mic setup code to the first click.
Also disposed the mic after the recording is completed.

(Gsoc'21) (Week-2) Fixes mic issues in recorder example

---

src/reverb.js

This updates the Reverb `_teardownConvolverNode()` method to disconnect the convolver node from input in so it can be GC'd. Fixes #650.

Fix memory leak in Reverb set() method

---

src/listener3d.js
src/panner3d.js

I regenerated the library files after correcting the typo.
This commit fixes #634 and also replaces all the files in `lib/` directory with the latest code.

Correct typo

---

src/amplitude.js
src/soundfile.js

Updated documentation of amplitude.disconnect() method with an example.

Updated aplitude.disconnect() method documentation

---

src/distortion.js
test/tests/p5.Distortion.js

- distortion.getAmount() now returns values between 0-1
- test for distortion now expects amount between 0-1
- fixed errors in documentation
- added example for distortion
- set works with amount=0 solving #652

fix distortion and add example

---

src/delay.js
src/effect.js
src/filter.js
src/panner3d.js
src/reverb.js

- renamed from "Signal" to "src" in Delay and Filter `process()` method documentation.
- added "This class extends [p5.Effect](https://p5js.org/reference/#/p5.Effect). Methods [amp()](https://p5js.org/reference/#/p5.Effect/amp), [chain()](https://p5js.org/reference/#/p5.Effect/chain), [drywet()](https://p5js.org/reference/#/p5.Effect/drywet), [connect()](https://p5js.org/reference/#/p5.Effect/connect), and [disconnect()](https://p5js.org/reference/#/p5.Effect/disconnect) are available." missing text in reverb and panner3d.
- added missing effects in the effect documentation.

fix inconsistency in documentation of effects

---

src/soundfile.js

Pan accepts two values ​​in SoundFile class, where the timeFromNow is optional but panValue is not optional.

panValue is not optional

---

src/oscillator.js

No reference was provided for userStartAudio(). And also the secondsFromNow is an optional parameter in p5.Oscillator.stop() method.
As we can see [here](https://github.com/processing/p5.js-sound/blob/main/src/oscillator.js#L207).

start_stop doc

---

src/compressor.js
test/tests/p5.Compressor.js

Resolves #710
- `Compressor.reduction()` now returns `this.compressor.reduction` instead of `this.compressor.reduction.value` since reduction doesn't have a value property
- test now uses `reduction()` instead of directly accesing the property with `compressor.compressor.reduction.value`

fix compressor.reduction()

---

test/tests/p5.EQ.js

When we pass 8 in the EQ constructor it takes some time to initialize the freq but we are checking just after the setting that's why it is comparing with the default value i.e 350. Same issue when we are setting the freq to 200. 
Resolved merge conflicts in PR https://github.com/processing/p5.js-sound/pull/615

(Chore) : Fixed merge conflicts in "fixing EQ test"

---

src/soundfile.js

Changed the documentation to reflect that the third argument is given to the callback as its only parameter (the time can be incorporated into that argument if required).
issue is here: https://github.com/processing/p5.js-sound/issues/672

documentation issue #672 re: callback params in p5.SoundFile addCue

---

src/fft.js

Addresses #665 (I am not closing the issue because I am not sure what should be done with negative numbers)
- `getEnergy()` now accepts 0 as a parameter
- Removed extra `else` statements
- Removed redundant `if`

fix FFT.getEnergy parameter validation

---

src/fft.js

Closes #665 
- Added validation for negative frequency values
- added 'frequency must be >= 0' to `getEnergy()` docs
- removed duplicate 'Energy' in docs

add negative number validation to `getEnergy()`

---

src/audioWorklet/ringBuffer.js
src/main.js
test/tests/p5.Amplitude.js
test/tests/p5.AudioIn.js
test/tests/p5.SoundFile.js
test/tests/p5.SoundRecorder.js

Did some Corrections in some existing tests and src files.
This PR is part of  some existing commits of PR #641

(Chore): Minor Corrections in some existing tests and src files

---

src/monosynth.js

added description for the various fields of `p5.MonoSynth reference` such as `decay`, `sustain` and `release`
resolves #727

(Docs): Updated various fields in the `p5.MonoSynth` reference

---

src/peakDetect.js

added description for the missing fields of `p5.PeakDetect reference` specifically for `isDetected`
resolves #734

(Docs) : added missing fields in p5.PeakDetect reference

---

src/effect.js
src/oscillator.js
src/panner.js
src/soundfile.js
test/tests/p5.Oscillator.js
test/tests/p5.Panner.js
test/tests/p5.SoundFile.js

Adresses #723, #303 
- `Panner.js` now extends `Effect.js`
- Added `getPan()` and `dispose()` methods to `Panner.js` 
- Modified `Oscillator.js` and `SoundFile.js` to work with the updated `Panner.js`
- Added documentation  and tests for `Panner.js`
For now, the `Panner.js` fallback for safari only works when used internally by `Oscillator.js` and `SoundFile.js`, does not extend `Effect.js` and does not have a `dispose()` method.

`Panner.js` rework

---

src/amplitude.js
src/audioVoice.js
src/audioin.js
src/effect.js
src/envelope.js
src/fft.js
src/gain.js
src/monosynth.js
src/oscillator.js
src/panner.js
src/polysynth.js
src/soundfile.js
test/tests/p5.Amplitude.js
test/tests/p5.AudioIn.js
test/tests/p5.AudioVoice.js
test/tests/p5.Effect.js
test/tests/p5.Envelope.js
test/tests/p5.Gain.js
test/tests/p5.MonoSynth.js
test/tests/p5.Oscillator.js
test/tests/p5.Panner.js
test/tests/p5.PolySynth.js
test/tests/p5.SoundFile.js

Closes #737 
- Classes with `connect(unit)` method now call `unit._onNewInput()` .
- Added `FFT._onNewInput()` so that FFT.js stops listening to all sound in the sketch when something is connected to it.
- Added tests for `._onNewInput()`.

add `_onNewInput()` hook 

---

src/oscillator.js
src/panner.js
src/soundfile.js
test/tests/p5.Panner.js
test/tests/p5.SoundFile.js

Closes #723 Adresses #303 
- The `Panner.js` fallback for safari<14.1 now works the same way as regular `Panner.js`, I think the only difference is that the `Panner.js` fallback does not accept an AudioParam to be connected in the `Panner.pan()` method.
- Updated `Oscillator.js` and `SoundFile.js` to work with `Panner.js`.
- Updated Tests.

update `Panner.js` fallback to extend `Effect.js`
